spring:
  application:
    name: hw7
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master-changelog.yaml
  datasource:
    url: jdbc:postgresql://localhost:5440/olimp
    username: superadmin
    password: superadmin
    driver-class-name: org.postgresql.Driver